/*
	Copyright 2017 by Christian Hüning (christianhuening@googlemail.com).

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/


package gitlabclient

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"
)

/*func TestGetFullContent(t *testing.T) {
	glContent, err := GetFullGitlabContent()
	if err != nil {
		t.Error(err)
	}
}*/

func TestGetAllGroups(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		//w.Header().Set("Link", `<https://gitlab.informatik.haw-hamburg.de/api/v4/groups?order_by=name&owned=false&page=2&per_page=20&sort=asc&statistics=false>; rel="next", <https://gitlab.informatik.haw-hamburg.de/api/v4/groups?order_by=name&owned=false&page=1&per_page=20&sort=asc&statistics=false>; rel="first", <https://gitlab.informatik.haw-hamburg.de/api/v4/groups?order_by=name&owned=false&page=17&per_page=20&sort=asc&statistics=false>; rel="last"`)
		fmt.Fprintln(w, `[
  {
    "id": 247,
    "name": "AA",
    "path": "AA",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AA",
    "request_access_enabled": false,
    "full_name": "AA",
    "full_path": "AA",
    "parent_id": null
  },
  {
    "id": 248,
    "name": "AAÜ",
    "path": "AAUe",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AAUe",
    "request_access_enabled": false,
    "full_name": "AAÜ",
    "full_path": "AAUe",
    "parent_id": null
  },
  {
    "id": 407,
    "name": "AD",
    "path": "AD",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AD",
    "request_access_enabled": false,
    "full_name": "AD",
    "full_path": "AD",
    "parent_id": null
  },
  {
    "id": 408,
    "name": "ADP",
    "path": "ADP",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/ADP",
    "request_access_enabled": false,
    "full_name": "ADP",
    "full_path": "ADP",
    "parent_id": null
  },
  {
    "id": 16,
    "name": "AES-Thesises",
    "path": "AES-Thesises",
    "description": "Migration von WebTing",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AES-Thesises",
    "request_access_enabled": false,
    "full_name": "AES-Thesises",
    "full_path": "AES-Thesises",
    "parent_id": null
  },
  {
    "id": 409,
    "name": "AF",
    "path": "AF",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AF",
    "request_access_enabled": false,
    "full_name": "AF",
    "full_path": "AF",
    "parent_id": null
  },
  {
    "id": 410,
    "name": "AFÜ",
    "path": "AFUe",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AFUe",
    "request_access_enabled": false,
    "full_name": "AFÜ",
    "full_path": "AFUe",
    "parent_id": null
  },
  {
    "id": 411,
    "name": "AI",
    "path": "AI",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AI",
    "request_access_enabled": false,
    "full_name": "AI",
    "full_path": "AI",
    "parent_id": null
  },
  {
    "id": 19,
    "name": "AI1_MB_AB",
    "path": "AI1_MB_AB",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AI1_MB_AB",
    "request_access_enabled": false,
    "full_name": "AI1_MB_AB",
    "full_path": "AI1_MB_AB",
    "parent_id": null
  },
  {
    "id": 412,
    "name": "AIP",
    "path": "AIP",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP",
    "request_access_enabled": false,
    "full_name": "AIP",
    "full_path": "AIP",
    "parent_id": null
  },
  {
    "id": 553,
    "name": "AIP-SS17-AEGIS",
    "path": "AIP-SS17-AEGIS",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP-SS17-AEGIS",
    "request_access_enabled": false,
    "full_name": "AIP-SS17-AEGIS",
    "full_path": "AIP-SS17-AEGIS",
    "parent_id": null
  },
  {
    "id": 550,
    "name": "AIP-SS17-AI-DA",
    "path": "AIP-SS17-AI-DA",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP-SS17-AI-DA",
    "request_access_enabled": false,
    "full_name": "AIP-SS17-AI-DA",
    "full_path": "AIP-SS17-AI-DA",
    "parent_id": null
  },
  {
    "id": 213,
    "name": "AIP-SS17-AIVengers",
    "path": "AIP-SS17-AIVengers",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP-SS17-AIVengers",
    "request_access_enabled": false,
    "full_name": "AIP-SS17-AIVengers",
    "full_path": "AIP-SS17-AIVengers",
    "parent_id": null
  },
  {
    "id": 551,
    "name": "AIP-SS17-aibros",
    "path": "AIP-SS17-aibros",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP-SS17-aibros",
    "request_access_enabled": false,
    "full_name": "AIP-SS17-aibros",
    "full_path": "AIP-SS17-aibros",
    "parent_id": null
  },
  {
    "id": 549,
    "name": "AIP-SS17-gofurther",
    "path": "AIP-SS17-gofurther",
    "description": "",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/AIP-SS17-gofurther",
    "request_access_enabled": false,
    "full_name": "AIP-SS17-gofurther",
    "full_path": "AIP-SS17-gofurther",
    "parent_id": null
  },
  {
    "id": 20,
    "name": "BA-Pro-Quadcopter",
    "path": "BA-Pro-Quadcopter",
    "description": "Migrated from WebTing",
    "visibility": "private",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/BA-Pro-Quadcopter",
    "request_access_enabled": false,
    "full_name": "BA-Pro-Quadcopter",
    "full_path": "BA-Pro-Quadcopter",
    "parent_id": null
  },
  {
    "id": 413,
    "name": "BS",
    "path": "BS",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/BS",
    "request_access_enabled": false,
    "full_name": "BS",
    "full_path": "BS",
    "parent_id": null
  },
  {
    "id": 414,
    "name": "BSP",
    "path": "BSP",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/BSP",
    "request_access_enabled": false,
    "full_name": "BSP",
    "full_path": "BSP",
    "parent_id": null
  },
  {
    "id": 415,
    "name": "BV",
    "path": "BV",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/BV",
    "request_access_enabled": false,
    "full_name": "BV",
    "full_path": "BV",
    "parent_id": null
  },
  {
    "id": 416,
    "name": "BVP",
    "path": "BVP",
    "description": "Dies ist eine Platzhalter Gruppe. Wenn Sie diesen Namen benötigen, wenden Sie sich bitte an gitlab-admin@informatik.haw-hamburg.de",
    "visibility": "public",
    "lfs_enabled": true,
    "avatar_url": null,
    "web_url": "https://gitlab.informatik.haw-hamburg.de/groups/BVP",
    "request_access_enabled": false,
    "full_name": "BVP",
    "full_path": "BVP",
    "parent_id": null
  }
]`)
	}))
	defer ts.Close()
	url := ts.URL
	groups := make([]GitlabGroup, 0)
	foundGroups, err := GetAllGroups(groups, url)
	if err != nil {
		t.Error(err)
	}
	if len(foundGroups) != 20 {
		t.Error("No groups were parsed.")
	}
}

func TestGetAllProjects(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintln(w, `[
  {
    "id": 643,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abq326/kubernetes-cat-application.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abq326/kubernetes-cat-application.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abq326/kubernetes-cat-application",
    "name": "kubernetes-cat-application",
    "name_with_namespace": "Philip Dakowitz / kubernetes-cat-application",
    "path": "kubernetes-cat-application",
    "path_with_namespace": "abq326/kubernetes-cat-application",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-09-01T19:17:24.856+02:00",
    "last_activity_at": "2017-09-01T19:17:24.856+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/643/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Philip Dakowitz",
      "username": "abq326",
      "id": 49,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/49/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abq326"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 49,
    "namespace": {
      "id": 74,
      "name": "abq326",
      "path": "abq326",
      "kind": "user",
      "full_path": "abq326",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 642,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:k8s400/k8s-application-sources.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/k8s400/k8s-application-sources.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/k8s400/k8s-application-sources",
    "name": "k8s-application-sources",
    "name_with_namespace": "k8s400 / k8s-application-sources",
    "path": "k8s-application-sources",
    "path_with_namespace": "k8s400/k8s-application-sources",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-09-01T15:29:50.989+02:00",
    "last_activity_at": "2017-09-01T15:29:50.989+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/642/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "k8s400",
      "username": "k8s400",
      "id": 316,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/0325e72d0f5e8370773aac08787293b8?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/k8s400"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 316,
    "namespace": {
      "id": 644,
      "name": "k8s400",
      "path": "k8s400",
      "kind": "user",
      "full_path": "k8s400",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 641,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abb256/k8s-application-sources.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abb256/k8s-application-sources.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abb256/k8s-application-sources",
      "name": "k8s-application-sources",
      "name_with_namespace": "Lukas Grundmann / k8s-application-sources",
      "path": "k8s-application-sources",
      "path_with_namespace": "abb256/k8s-application-sources",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-09-01T15:15:52.300+02:00",
      "last_activity_at": "2017-09-01T15:15:52.300+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 641,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abb256/k8s-application-sources.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abb256/k8s-application-sources.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abb256/k8s-application-sources",
    "name": "k8s-application-sources",
    "name_with_namespace": "Lukas Grundmann / k8s-application-sources",
    "path": "k8s-application-sources",
    "path_with_namespace": "abb256/k8s-application-sources",
    "star_count": 0,
    "forks_count": 1,
    "created_at": "2017-09-01T15:15:52.300+02:00",
    "last_activity_at": "2017-09-01T15:15:52.300+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/641/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Lukas Grundmann",
      "username": "abb256",
      "id": 41,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/b67f609c1119e8f464d32ac99d093300?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abb256"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 41,
    "namespace": {
      "id": 66,
      "name": "abb256",
      "path": "abb256",
      "kind": "user",
      "full_path": "abb256",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 639,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:sage/kubectl.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/sage/kubectl.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/sage/kubectl",
    "name": "kubectl",
    "name_with_namespace": "Lutz Behnke / kubectl",
    "path": "kubectl",
    "path_with_namespace": "sage/kubectl",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-31T10:24:29.542+02:00",
    "last_activity_at": "2017-08-31T16:33:40.243+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/639/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Lutz Behnke",
      "username": "sage",
      "id": 6,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/6/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/sage"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 6,
    "namespace": {
      "id": 7,
      "name": "sage",
      "path": "sage",
      "kind": "user",
      "full_path": "sage",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 638,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:icc/kubectl.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/icc/kubectl.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/icc/kubectl",
      "name": "kubectl",
      "name_with_namespace": "icc / kubectl",
      "path": "kubectl",
      "path_with_namespace": "icc/kubectl",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-08-30T18:09:34.197+02:00",
      "last_activity_at": "2017-08-30T18:09:34.197+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 638,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:icc/kubectl.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/icc/kubectl.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/icc/kubectl",
    "name": "kubectl",
    "name_with_namespace": "icc / kubectl",
    "path": "kubectl",
    "path_with_namespace": "icc/kubectl",
    "star_count": 0,
    "forks_count": 1,
    "created_at": "2017-08-30T18:09:34.197+02:00",
    "last_activity_at": "2017-08-30T18:09:34.197+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/638/members"
    },
    "archived": false,
    "visibility": "private",
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 7,
    "namespace": {
      "id": 75,
      "name": "icc",
      "path": "icc",
      "kind": "group",
      "full_path": "icc",
      "parent_id": null,
      "members_count_with_descendants": 3
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 637,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:aaz343/k8s-job-monitor.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/aaz343/k8s-job-monitor.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/aaz343/k8s-job-monitor",
    "name": "k8s-job-monitor",
    "name_with_namespace": "Christian Hüning / k8s-job-monitor",
    "path": "k8s-job-monitor",
    "path_with_namespace": "aaz343/k8s-job-monitor",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-27T11:17:43.538+02:00",
    "last_activity_at": "2017-08-29T09:48:10.029+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/637/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Christian Hüning",
      "username": "aaz343",
      "id": 7,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/7/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/aaz343"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 7,
    "namespace": {
      "id": 9,
      "name": "aaz343",
      "path": "aaz343",
      "kind": "user",
      "full_path": "aaz343",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 531,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/k8s-job-monitor.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/k8s-job-monitor.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/k8s-job-monitor",
      "name": "k8s-job-monitor",
      "name_with_namespace": "timadorus / k8s-job-monitor",
      "path": "k8s-job-monitor",
      "path_with_namespace": "timadorus/k8s-job-monitor",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-06-08T10:19:21.349+02:00",
      "last_activity_at": "2017-08-30T16:25:01.333+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 636,
    "description": null,
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abz826/nao-plays.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abz826/nao-plays.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abz826/nao-plays",
    "name": "nao-plays",
    "name_with_namespace": "abz826 / nao-plays",
    "path": "nao-plays",
    "path_with_namespace": "abz826/nao-plays",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-26T07:10:56.455+02:00",
    "last_activity_at": "2017-08-30T21:06:02.306+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/636/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "chris",
      "username": "abz826",
      "id": 317,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/f139b5b140569969070e387ec3cbc83f?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abz826"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 317,
    "namespace": {
      "id": 645,
      "name": "abz826",
      "path": "abz826",
      "kind": "user",
      "full_path": "abz826",
      "parent_id": null
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": true,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 635,
    "description": "Quellecode zu den Lehrveranstaltungen",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abo781/lehre.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abo781/lehre.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abo781/lehre",
    "name": "lehre",
    "name_with_namespace": "Philipp Jenke / lehre",
    "path": "lehre",
    "path_with_namespace": "abo781/lehre",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-24T16:36:49.104+02:00",
    "last_activity_at": "2017-08-24T16:36:49.104+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/635/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Philipp Jenke",
      "username": "abo781",
      "id": 86,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a67f78943aa2a5980d6ced6abf1a19f8?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abo781"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 86,
    "namespace": {
      "id": 115,
      "name": "abo781",
      "path": "abo781",
      "kind": "user",
      "full_path": "abo781",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 632,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abg657/quperl_admin_client.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_admin_client.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_admin_client",
    "name": "quperl_admin_client",
    "name_with_namespace": "Sven Allers / quperl_admin_client",
    "path": "quperl_admin_client",
    "path_with_namespace": "abg657/quperl_admin_client",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-23T13:07:39.348+02:00",
    "last_activity_at": "2017-08-30T15:11:24.243+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/632/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Sven Allers",
      "username": "abg657",
      "id": 12,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a20287c7d999ed5c512889b1659225ad?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 12,
    "namespace": {
      "id": 15,
      "name": "abg657",
      "path": "abg657",
      "kind": "user",
      "full_path": "abg657",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 127,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/quperl_admin_client.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_admin_client.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_admin_client",
      "name": "quperl_admin_client",
      "name_with_namespace": "timadorus / quperl_admin_client",
      "path": "quperl_admin_client",
      "path_with_namespace": "timadorus/quperl_admin_client",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-02-21T14:22:01.860+01:00",
      "last_activity_at": "2017-08-30T09:19:48.147+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 631,
    "description": "arbitrary spaces in octree",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abg657/quperl_octree2.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_octree2.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_octree2",
    "name": "quperl_octree2",
    "name_with_namespace": "Sven Allers / quperl_octree2",
    "path": "quperl_octree2",
    "path_with_namespace": "abg657/quperl_octree2",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-23T13:07:34.860+02:00",
    "last_activity_at": "2017-08-23T13:07:34.860+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/631/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Sven Allers",
      "username": "abg657",
      "id": 12,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a20287c7d999ed5c512889b1659225ad?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 12,
    "namespace": {
      "id": 15,
      "name": "abg657",
      "path": "abg657",
      "kind": "user",
      "full_path": "abg657",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 9,
      "description": "arbitrary spaces in octree",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/quperl_octree2.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_octree2.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_octree2",
      "name": "quperl_octree2",
      "name_with_namespace": "timadorus / quperl_octree2",
      "path": "quperl_octree2",
      "path_with_namespace": "timadorus/quperl_octree2",
      "star_count": 0,
      "forks_count": 2,
      "created_at": "2016-12-12T14:56:31.719+01:00",
      "last_activity_at": "2017-09-03T10:42:35.290+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 630,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abg657/quperl_control.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_control.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_control",
    "name": "quperl_control",
    "name_with_namespace": "Sven Allers / quperl_control",
    "path": "quperl_control",
    "path_with_namespace": "abg657/quperl_control",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-23T13:07:28.659+02:00",
    "last_activity_at": "2017-08-23T13:07:28.659+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/630/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Sven Allers",
      "username": "abg657",
      "id": 12,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a20287c7d999ed5c512889b1659225ad?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 12,
    "namespace": {
      "id": 15,
      "name": "abg657",
      "path": "abg657",
      "kind": "user",
      "full_path": "abg657",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 89,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/quperl_control.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_control.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_control",
      "name": "quperl_control",
      "name_with_namespace": "timadorus / quperl_control",
      "path": "quperl_control",
      "path_with_namespace": "timadorus/quperl_control",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-01-25T12:17:30.026+01:00",
      "last_activity_at": "2017-05-26T10:15:37.924+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 629,
    "description": "server providing persistent storage for a distributed virtual environment.",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abg657/quperl_server.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_server.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_server",
    "name": "quperl_server",
    "name_with_namespace": "Sven Allers / quperl_server",
    "path": "quperl_server",
    "path_with_namespace": "abg657/quperl_server",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-23T13:07:17.524+02:00",
    "last_activity_at": "2017-08-30T15:11:25.509+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/629/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Sven Allers",
      "username": "abg657",
      "id": 12,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a20287c7d999ed5c512889b1659225ad?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 12,
    "namespace": {
      "id": 15,
      "name": "abg657",
      "path": "abg657",
      "kind": "user",
      "full_path": "abg657",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 88,
      "description": "server providing persistent storage for a distributed virtual environment.",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/quperl_server.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_server.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_server",
      "name": "quperl_server",
      "name_with_namespace": "timadorus / quperl_server",
      "path": "quperl_server",
      "path_with_namespace": "timadorus/quperl_server",
      "star_count": 0,
      "forks_count": 1,
      "created_at": "2017-01-24T22:01:35.805+01:00",
      "last_activity_at": "2017-06-20T07:49:12.288+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 628,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abg657/quperl_client.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_client.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657/quperl_client",
    "name": "quperl_client",
    "name_with_namespace": "Sven Allers / quperl_client",
    "path": "quperl_client",
    "path_with_namespace": "abg657/quperl_client",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-23T13:07:05.175+02:00",
    "last_activity_at": "2017-08-23T13:07:05.175+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/628/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Sven Allers",
      "username": "abg657",
      "id": 12,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/a20287c7d999ed5c512889b1659225ad?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abg657"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 12,
    "namespace": {
      "id": 15,
      "name": "abg657",
      "path": "abg657",
      "kind": "user",
      "full_path": "abg657",
      "parent_id": null
    },
    "forked_from_project": {
      "id": 17,
      "description": "",
      "default_branch": "master",
      "tag_list": [],
      "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:timadorus/quperl_client.git",
      "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_client.git",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/timadorus/quperl_client",
      "name": "quperl_client",
      "name_with_namespace": "timadorus / quperl_client",
      "path": "quperl_client",
      "path_with_namespace": "timadorus/quperl_client",
      "star_count": 0,
      "forks_count": 2,
      "created_at": "2016-12-20T10:57:42.029+01:00",
      "last_activity_at": "2017-09-04T19:38:09.632+02:00"
    },
    "import_status": "finished",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 627,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:sarstedt/se1basis.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/sarstedt/se1basis.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/sarstedt/se1basis",
    "name": "se1basis",
    "name_with_namespace": "Stefan Sarstedt / se1basis",
    "path": "se1basis",
    "path_with_namespace": "sarstedt/se1basis",
    "star_count": 1,
    "forks_count": 0,
    "created_at": "2017-08-22T11:10:41.602+02:00",
    "last_activity_at": "2017-08-22T21:39:27.028+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/627/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Stefan Sarstedt",
      "username": "sarstedt",
      "id": 13,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/13/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/sarstedt"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": true,
    "lfs_enabled": true,
    "creator_id": 13,
    "namespace": {
      "id": 37,
      "name": "sarstedt",
      "path": "sarstedt",
      "kind": "user",
      "full_path": "sarstedt",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 626,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abb256/k8sworkshop.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abb256/k8sworkshop.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abb256/k8sworkshop",
    "name": "k8sworkshop",
    "name_with_namespace": "Lukas Grundmann / k8sworkshop",
    "path": "k8sworkshop",
    "path_with_namespace": "abb256/k8sworkshop",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-21T17:08:24.381+02:00",
    "last_activity_at": "2017-09-03T05:32:29.406+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/626/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Lukas Grundmann",
      "username": "abb256",
      "id": 41,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/b67f609c1119e8f464d32ac99d093300?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abb256"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 41,
    "namespace": {
      "id": 66,
      "name": "abb256",
      "path": "abb256",
      "kind": "user",
      "full_path": "abb256",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 625,
    "description": "",
    "default_branch": null,
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:James-dein-helfer/nao-app.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/James-dein-helfer/nao-app.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/James-dein-helfer/nao-app",
    "name": "nao-app",
    "name_with_namespace": "James-dein-helfer / nao-app",
    "path": "nao-app",
    "path_with_namespace": "James-dein-helfer/nao-app",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-18T16:44:20.255+02:00",
    "last_activity_at": "2017-08-18T16:44:20.255+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/625/members"
    },
    "archived": false,
    "visibility": "private",
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 265,
    "namespace": {
      "id": 639,
      "name": "James-dein-helfer",
      "path": "James-dein-helfer",
      "kind": "group",
      "full_path": "James-dein-helfer",
      "parent_id": null,
      "members_count_with_descendants": 5
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 623,
    "description": "",
    "default_branch": null,
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:James-dein-helfer/server.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/James-dein-helfer/server.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/James-dein-helfer/server",
    "name": "server",
    "name_with_namespace": "James-dein-helfer / server",
    "path": "server",
    "path_with_namespace": "James-dein-helfer/server",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-18T16:42:39.926+02:00",
    "last_activity_at": "2017-08-18T16:42:39.926+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/623/members"
    },
    "archived": false,
    "visibility": "private",
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 265,
    "namespace": {
      "id": 639,
      "name": "James-dein-helfer",
      "path": "James-dein-helfer",
      "kind": "group",
      "full_path": "James-dein-helfer",
      "parent_id": null,
      "members_count_with_descendants": 5
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 621,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:aca361/aDGVM-vegetation-generator.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/aca361/aDGVM-vegetation-generator.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/aca361/aDGVM-vegetation-generator",
    "name": "aDGVM-vegetation-generator",
    "name_with_namespace": "Julius Weyl / aDGVM-vegetation-generator",
    "path": "aDGVM-vegetation-generator",
    "path_with_namespace": "aca361/aDGVM-vegetation-generator",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-18T06:56:55.346+02:00",
    "last_activity_at": "2017-08-19T11:23:14.228+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/621/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "Julius Weyl",
      "username": "aca361",
      "id": 45,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/45/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/aca361"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 45,
    "namespace": {
      "id": 70,
      "name": "aca361",
      "path": "aca361",
      "kind": "user",
      "full_path": "aca361",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 620,
    "description": "",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:abf617/thesis.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/abf617/thesis.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abf617/thesis",
    "name": "thesis",
    "name_with_namespace": "abf617 / thesis",
    "path": "thesis",
    "path_with_namespace": "abf617/thesis",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-16T23:27:02.063+02:00",
    "last_activity_at": "2017-08-22T00:10:31.224+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/620/members"
    },
    "archived": false,
    "visibility": "private",
    "owner": {
      "name": "abf617",
      "username": "abf617",
      "id": 308,
      "state": "active",
      "avatar_url": "https://secure.gravatar.com/avatar/f93f5c620343be9b9b32820991b38677?s=80\u0026d=identicon",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/abf617"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 308,
    "namespace": {
      "id": 635,
      "name": "abf617",
      "path": "abf617",
      "kind": "user",
      "full_path": "abf617",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  },
  {
    "id": 619,
    "description": "Web-Executor: will run a command from a shell on a linux machine when being called via https. The command can be configured.",
    "default_branch": "master",
    "tag_list": [],
    "ssh_url_to_repo": "git@gitlab.informatik.haw-hamburg.de:sage/wexecutor.git",
    "http_url_to_repo": "https://gitlab.informatik.haw-hamburg.de/sage/wexecutor.git",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/sage/wexecutor",
    "name": "wexecutor",
    "name_with_namespace": "Lutz Behnke / wexecutor",
    "path": "wexecutor",
    "path_with_namespace": "sage/wexecutor",
    "star_count": 0,
    "forks_count": 0,
    "created_at": "2017-08-16T11:08:08.003+02:00",
    "last_activity_at": "2017-08-16T11:08:08.003+02:00",
    "_links": {
      "self": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619",
      "issues": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/issues",
      "merge_requests": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/merge_requests",
      "repo_branches": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/repository/branches",
      "labels": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/labels",
      "events": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/events",
      "members": "http://gitlab.informatik.haw-hamburg.de/api/v4/projects/619/members"
    },
    "archived": false,
    "visibility": "public",
    "owner": {
      "name": "Lutz Behnke",
      "username": "sage",
      "id": 6,
      "state": "active",
      "avatar_url": "https://gitlab.informatik.haw-hamburg.de/uploads/-/system/user/avatar/6/avatar.png",
      "web_url": "https://gitlab.informatik.haw-hamburg.de/sage"
    },
    "container_registry_enabled": true,
    "issues_enabled": true,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "jobs_enabled": true,
    "snippets_enabled": true,
    "shared_runners_enabled": false,
    "lfs_enabled": true,
    "creator_id": 6,
    "namespace": {
      "id": 7,
      "name": "sage",
      "path": "sage",
      "kind": "user",
      "full_path": "sage",
      "parent_id": null
    },
    "import_status": "none",
    "avatar_url": null,
    "open_issues_count": 0,
    "public_jobs": true,
    "ci_config_path": null,
    "shared_with_groups": [],
    "only_allow_merge_if_pipeline_succeeds": false,
    "request_access_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "printing_merge_request_link_enabled": true,
    "permissions": {
      "project_access": null,
      "group_access": null
    }
  }
]`)
	}))
	defer ts.Close()
	url := ts.URL
	foundProjects, err := GetAllProjects(make([]GitlabProject, 0), url)
	if err != nil {
		t.Error(err)
	}
	if len(foundProjects) != 20 {
		t.Error("No projects were parsed.")
	}
}

func TestGetAllUsers(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintln(w, `[
  {
    "name": "abt897",
    "username": "abt897",
    "id": 319,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/c8576a54f032360762b26c5ba5cb1f0d?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abt897",
    "created_at": "2017-08-30T19:52:55.712+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-30T19:52:55.818+02:00",
    "confirmed_at": "2017-08-30T19:52:55.489+02:00",
    "last_activity_on": "2017-08-30",
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-30T19:52:55.818+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acf462",
    "username": "acf462",
    "id": 318,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/f973967b954fd7b2e91bd84854bc276e?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acf462",
    "created_at": "2017-08-30T16:00:50.425+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-30T16:00:50.535+02:00",
    "confirmed_at": "2017-08-30T16:00:50.097+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-30T16:00:50.535+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "chris",
    "username": "abz826",
    "id": 317,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/f139b5b140569969070e387ec3cbc83f?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abz826",
    "created_at": "2017-08-26T06:48:16.347+02:00",
    "bio": "",
    "location": "Hamburg",
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": "",
    "last_sign_in_at": "2017-08-29T10:18:25.828+02:00",
    "confirmed_at": "2017-08-26T06:48:16.331+02:00",
    "last_activity_on": "2017-08-30",
    "email": "chris.thiele@haw-hamburg.de",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-30T19:13:09.218+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "k8s400",
    "username": "k8s400",
    "id": 316,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/0325e72d0f5e8370773aac08787293b8?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/k8s400",
    "created_at": "2017-08-25T10:59:49.080+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-25T10:59:49.161+02:00",
    "confirmed_at": "2017-08-25T10:59:48.841+02:00",
    "last_activity_on": null,
    "email": "students001.k@informatik.haw-hamburg.de",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-09-01T15:09:06.784+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abv898",
    "username": "abv898",
    "id": 315,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/9845c9b279dd6d1017d27edc068af074?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abv898",
    "created_at": "2017-08-23T21:51:13.826+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-23T21:51:13.889+02:00",
    "confirmed_at": "2017-08-23T21:51:13.782+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-23T21:51:13.889+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acb980",
    "username": "acb980",
    "id": 314,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/181abffc7a76c3fced7d569d8efc9676?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acb980",
    "created_at": "2017-08-23T21:50:34.014+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-23T21:50:34.094+02:00",
    "confirmed_at": "2017-08-23T21:50:33.980+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-23T21:50:34.094+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acc412",
    "username": "acc412",
    "id": 313,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/0ee8b8b64f13d45c721394c819150f31?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acc412",
    "created_at": "2017-08-22T21:39:43.004+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-22T21:39:43.064+02:00",
    "confirmed_at": "2017-08-22T21:39:42.490+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-22T21:39:43.064+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abf159",
    "username": "abf159",
    "id": 312,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/1b9b9b6c19e07ea5c2863a512f242b82?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abf159",
    "created_at": "2017-08-21T23:21:03.050+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-21T23:21:03.113+02:00",
    "confirmed_at": "2017-08-21T23:21:02.697+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-22T09:56:59.416+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acj141",
    "username": "acj141",
    "id": 311,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/14311c01b7d60387a4aea8eb01b57d1a?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acj141",
    "created_at": "2017-08-16T20:43:42.973+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-16T20:43:43.044+02:00",
    "confirmed_at": "2017-08-16T20:43:42.123+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-16T20:43:43.044+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abz908",
    "username": "abz908",
    "id": 310,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/065ee13e2c8603b536ef9046e69cb40a?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abz908",
    "created_at": "2017-08-15T20:26:51.718+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-15T20:26:51.792+02:00",
    "confirmed_at": "2017-08-15T20:26:51.704+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-15T20:26:51.792+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abq335",
    "username": "abq335",
    "id": 309,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/406221c71e5ca1729b99fd84737792e3?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abq335",
    "created_at": "2017-08-15T19:35:35.871+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-28T10:06:33.104+02:00",
    "confirmed_at": "2017-08-15T19:35:35.856+02:00",
    "last_activity_on": "2017-08-28",
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-09-05T12:25:14.391+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abf617",
    "username": "abf617",
    "id": 308,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/f93f5c620343be9b9b32820991b38677?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abf617",
    "created_at": "2017-08-15T17:11:01.938+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-21T23:33:57.117+02:00",
    "confirmed_at": "2017-08-15T17:11:01.922+02:00",
    "last_activity_on": "2017-08-22",
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 5,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-22T12:42:17.235+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acj102",
    "username": "acj102",
    "id": 307,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/fe86c8a482560eb9d0dff52979448497?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acj102",
    "created_at": "2017-08-15T12:27:09.512+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-15T12:27:09.632+02:00",
    "confirmed_at": "2017-08-15T12:27:09.350+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-15T12:27:09.632+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "aci959",
    "username": "aci959",
    "id": 306,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/2150bbc122c3430719391d90c3302524?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/aci959",
    "created_at": "2017-08-11T21:11:31.062+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-11T21:11:31.165+02:00",
    "confirmed_at": "2017-08-11T21:11:30.745+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-11T21:11:31.165+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "ach146",
    "username": "ach146",
    "id": 305,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/df1ed92a44ac8a67ff4fad0ef107875f?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/ach146",
    "created_at": "2017-08-10T09:19:44.771+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-10T09:19:44.828+02:00",
    "confirmed_at": "2017-08-10T09:19:44.754+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-10T09:19:44.828+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "aav300",
    "username": "aav300",
    "id": 304,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/ff76518c28711c5c95deaf794034c034?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/aav300",
    "created_at": "2017-08-09T19:57:00.500+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-09T19:57:00.553+02:00",
    "confirmed_at": "2017-08-09T19:57:00.486+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-09T19:57:00.553+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abd260",
    "username": "abd260",
    "id": 303,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/974d7fdb9a76fade73d2c56973955dfb?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abd260",
    "created_at": "2017-08-09T19:35:13.794+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-09T19:35:13.863+02:00",
    "confirmed_at": "2017-08-09T19:35:13.531+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-09T19:35:13.863+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "aci829",
    "username": "aci829",
    "id": 302,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/d94514dbf168361ce18f150cd6f85590?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/aci829",
    "created_at": "2017-08-09T16:17:06.553+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-09T16:17:06.610+02:00",
    "confirmed_at": "2017-08-09T16:17:06.192+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-09T16:17:06.610+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "abr561",
    "username": "abr561",
    "id": 301,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/9ec28ae03efebf4f45c18ffd874c3f6a?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/abr561",
    "created_at": "2017-08-09T14:39:34.700+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-09T14:39:34.756+02:00",
    "confirmed_at": "2017-08-09T14:39:34.683+02:00",
    "last_activity_on": null,
    "email": "max.mustermann@test-gl-k8s.com",
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-09T14:39:34.756+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  },
  {
    "name": "acc166",
    "username": "acc166",
    "id": 300,
    "state": "active",
    "avatar_url": "https://secure.gravatar.com/avatar/d30f0e7e053bbf3fcc65d5b8aee2f529?s=80\u0026d=identicon",
    "web_url": "https://gitlab.informatik.haw-hamburg.de/acc166",
    "created_at": "2017-08-09T14:13:22.402+02:00",
    "bio": null,
    "location": null,
    "skype": "",
    "linkedin": "",
    "twitter": "",
    "website_url": "",
    "organization": null,
    "last_sign_in_at": "2017-08-09T14:13:22.470+02:00",
    "confirmed_at": "2017-08-09T14:13:22.386+02:00",
    "last_activity_on": null,
    "color_scheme_id": 1,
    "projects_limit": 10,
    "current_sign_in_at": "2017-08-09T14:13:22.470+02:00",
    "identities": [
      {
        "provider": "ldapmain",
        "extern_uid": "uid=123xyc,ou=Users,ou=dept,o=test-company"
      }
    ],
    "can_create_group": true,
    "can_create_project": true,
    "two_factor_enabled": false,
    "external": false,
    "is_admin": false
  }
]`)
	}))
	defer ts.Close()
	url := ts.URL
	foundUsers, err := GetAllUsers(make([]GitlabUser, 0), url)
	if err != nil {
		t.Error(err)
	}
	if len(foundUsers) != 20 {
		t.Error("No users were parsed.")
	}
}
